"""add tag to jobs and webhooks table

Revision ID: bad30ed4885a
Revises: 02283072aa0f
Create Date: 2025-11-28 14:48:30.613934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad30ed4885a'
down_revision: Union[str, Sequence[str], None] = '02283072aa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tag'), 'webhooks', ['tag'], unique=False)
    op.add_column('agent_jobs', sa.Column('tag', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_agent_jobs_tag'), 'agent_jobs', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_jobs_tag'), table_name='agent_jobs')
    op.drop_column('agent_jobs', 'tag')
    op.drop_index(op.f('ix_webhooks_tag'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
