"""Oblique Strategies by Brian Eno and Peter Schmidt."""

OBLIQUE_STRATEGIES = [
    "Abandon desire",
    "Abandon normal instructions",
    "Accept advice",
    "Adding on",
    "A line has two sides",
    "Allow an easement (an easement is the abandonment of a stricture)",
    "Always the first steps",
    "Are there sections? Consider transitions",
    "Ask people to work against their better judgement",
    "Ask your body",
    "Assemble some of the elements in a group and treat the group",
    "Balance the consistency principle with the inconsistency principle",
    "Be dirty",
    "Be extravagant",
    "Be less critical",
    "Breathe more deeply",
    "Bridges - build - burn",
    "Cascades",
    "Change ambiguities to specifics",
    "Change instrument roles",
    "Change nothing and continue consistently",
    "Change specifics to ambiguities",
    "Children - speaking - singing",
    "Cluster analysis",
    "Consider different fading systems",
    "Consider transitions",
    "Consult other sources - promising - unpromising",
    "Convert a melodic element into a rhythmic element",
    "Courage!",
    "Cut a vital connection",
    "Decorate, decorate",
    "Define an area as 'safe' and use it as an anchor",
    "Destroy - nothing - the most important thing",
    "Discard an axiom",
    "Disciplined self-indulgence",
    "Disconnect from desire",
    "Discover your formulas and abandon them",
    "Display your talent",
    "Distort time",
    "Do nothing for as long as possible",
    "Do something boring",
    "Do something sudden, destructive and unpredictable",
    "Do the last thing first",
    "Do the words need changing?",
    "Do we need holes?",
    "Emphasize differences",
    "Emphasize repetitions",
    "Emphasize the flaws",
    "Faced with a choice, do both",
    "Feed the recording back out of the medium",
    "Fill every beat with something",
    "Find a safe part and use it as a anchor",
    "Get your neck massaged",
    "Ghost echoes",
    "Give the game away",
    "Give way to your worst impulse",
    "Go outside. Shut the door.",
    "Go to an extreme, come part way back",
    "How would someone else do it?",
    "How would you have done it?",
    "Humanize something free of error",
    "Imagine the piece as a set of disconnected events",
    "In total darkness, or in a very large room, very quietly",
    "Intentions - nobility of - humility of - credibility of",
    "Into the impossible",
    "Is it finished?",
    "Is something missing?",
    "Is the intonation correct?",
    "Is the style right?",
    "Is there something missing?",
    "It is quite possible (after all)",
    "Just carry on",
    "Left channel, right channel, center channel",
    "Listen to the quiet voice",
    "Look at the order in which you do things",
    "Look closely at the most embarrassing details and amplify them",
    "Lost in useless territory",
    "Lowest common denominator",
    "Magnify the most difficult details",
    "Make a blank valuable by putting it in an exquisite frame",
    "Make it more sensual",
    "Make what's perfect more human",
    "Mechanize something idiosyncratic",
    "Move towards the unimportant",
    "Mute and continue",
    "Not building a wall; making a brick",
    "Once the search has begun, something will be found",
    "Only a part, not the whole",
    "Only one element of each kind",
    "Openly resist change",
    "Overtly resist change",
    "Put in earplugs",
    "Question the heroic",
    "Reevaluation (a warm feeling)",
    "Remember quiet evenings",
    "Remove a restriction",
    "Remove ambiguities and convert to specifics",
    "Remove specifics and convert to ambiguities",
    "Repetition is a form of change",
    "Reverse",
    "Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
    "Shut the door and listen from outside",
    "Simple Subtraction",
    "Simply a matter of work",
    "Spectrum analysis",
    "State the problem as clearly as possible",
    "Take a break",
    "Take away the elements in order of apparent non-importance",
    "Tape your mouth",
    "The inconsistency principle",
    "The most easily forgotten thing is the most important",
    "The most important thing is the thing most easily forgotten",
    "The tape is now the music",
    "Think - inside the work - outside the work",
    "Think of the radio",
    "Tidy up",
    "Trust in the you of now",
    "Turn it upside down",
    "Twist the spine",
    "Use 'unqualified' people",
    "Use an old idea",
    "Use an unacceptable color",
    "Use cliches",
    "Use fewer notes",
    "Use filters",
    "Use something nearby as a model",
    "Use your own ideas",
    "Voice your suspicions",
    "Water",
    "What are the sections sections of? Imagine a caterpillar moving",
    "What are you really thinking about just now?",
    "What context would look right?",
    "What is the reality of the situation?",
    "What is the simplest solution?",
    "What mistakes did you make last time?",
    "What to increase? What to reduce? What to maintain?",
    "What were you really thinking about just now?",
    "What would your closest friend do?",
    "When is it for?",
    "Where is the edge?",
    "Which parts can be grouped?",
    "Work at a different speed",
    "You are an engineer",
    "You can only make one dot at a time",
    "You don't have to be ashamed of using your own ideas",
]
